### ISSUE TITLE
Delete Post function

### ISSUE THREAD

**Issue by jeffrey1981** [jeffrey1981/sad_pizza#1]
I am unable to complete the delete functionality for a post. I have created a button with the path directing to the post controller and destroy.html. 

The error reads:

undefined method `destroy_post_path' for #<#Class:0x007f9d15ccb528:0x007f9d153e0990>

detroy.html.erd code.

https://i.imgur.com/kDzfEit.png

post_controller code

https://i.imgur.com/wX5sJz9.png

botton code in show.html.erb

https://i.imgur.com/tF2BKkV.png

If you need any further information i am happy to provide.
cheers!

**Comment by tambling** [comment]
Make sure you have `:destroy` in your `resources :posts` in your `routes.rb` file.

**Comment by jeffrey1981** [comment]
On my 1 to 1 Phile had me remove all the methods in the posts resource as I would be using all of them.

**Comment by tambling** [comment]
Show me the output of `rake routes`.

**Comment by tambling** [comment]
Also, note that there probably won't be a prefix called `destroy_posts`– instead, you're sending a `DELETE` request to `posts_path`.

**Comment by jeffrey1981** [comment]
ahhhh, thank you!!!

**Comment by tambling** [comment]
:pray:
